# Generated by Django 5.2.4 on 2025-07-12 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collage',
            name='layout_config',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
