# Generated by Django 5.2.4 on 2025-07-12 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collage', '0002_collage_layout_config'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imageitem',
            options={'ordering': ['position']},
        ),
        migrations.RemoveField(
            model_name='collage',
            name='layout_config',
        ),
        migrations.AddField(
            model_name='imageitem',
            name='height',
            field=models.IntegerField(default=0, help_text='Height in pixels'),
        ),
        migrations.AddField(
            model_name='imageitem',
            name='position',
            field=models.IntegerField(default=0, help_text='Position in the collage'),
        ),
        migrations.AddField(
            model_name='imageitem',
            name='width',
            field=models.IntegerField(default=0, help_text='Width in pixels'),
        ),
        migrations.AddField(
            model_name='imageitem',
            name='x_position',
            field=models.IntegerField(default=0, help_text='X position in collage'),
        ),
        migrations.AddField(
            model_name='imageitem',
            name='y_position',
            field=models.IntegerField(default=0, help_text='Y position in collage'),
        ),
    ]
