# Generated by Django 5.2.4 on 2025-07-12 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collage', '0003_alter_imageitem_options_remove_collage_layout_config_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collage',
            name='layout_config',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='collage',
            name='layout_type',
            field=models.CharField(choices=[('grid', 'Grid Layout'), ('seamless', 'Seamless Layout'), ('masonry', 'Masonry Layout'), ('custom', 'Custom Layout')], default='grid', max_length=20),
        ),
        migrations.AddField(
            model_name='imageitem',
            name='rotation',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='imageitem',
            name='z_index',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='imageitem',
            name='height',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='imageitem',
            name='position',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='imageitem',
            name='width',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='imageitem',
            name='x_position',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='imageitem',
            name='y_position',
            field=models.IntegerField(default=0),
        ),
    ]
