# Generated by Django 5.2.4 on 2025-07-12 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collage', '0004_collage_layout_config_collage_layout_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imageitem',
            options={},
        ),
        migrations.RemoveField(
            model_name='collage',
            name='layout_config',
        ),
        migrations.RemoveField(
            model_name='collage',
            name='layout_type',
        ),
        migrations.RemoveField(
            model_name='imageitem',
            name='height',
        ),
        migrations.RemoveField(
            model_name='imageitem',
            name='position',
        ),
        migrations.RemoveField(
            model_name='imageitem',
            name='rotation',
        ),
        migrations.RemoveField(
            model_name='imageitem',
            name='width',
        ),
        migrations.RemoveField(
            model_name='imageitem',
            name='x_position',
        ),
        migrations.RemoveField(
            model_name='imageitem',
            name='y_position',
        ),
        migrations.RemoveField(
            model_name='imageitem',
            name='z_index',
        ),
    ]
