# Generated by Django 5.2.4 on 2025-07-12 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collage', '0005_alter_imageitem_options_remove_collage_layout_config_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collage',
            name='grid_style',
            field=models.CharField(choices=[('2x2', '2x2 Grid'), ('3x3', '3x3 Grid'), ('4x4', '4x4 Grid'), ('2x3', '2x3 Grid'), ('3x2', '3x2 Grid'), ('4x3', '4x3 Grid'), ('3x4', '3x4 Grid')], default='3x3', max_length=10),
        ),
    ]
